version: '3'
services:
  db:
    # build: ./db
    image: mysql
    container_name: mysql
    command: "--default-authentication-plugin=mysql_native_password"
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: server